---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
suites:
- name: default
  run_list: 
  - recipe[nfs_media]
  attributes: {}
